### ISSUE TITLE
NPA for entire Europe

### ISSUE THREAD

**Issue by andrixnet** [flopp/FloppsMap#42]
Currently (according to info in translation files) only NPA in Germany are featured.

Is it possible to extend this to cover (at least) the entire EU? (if not entire Europe, non-EU countries included).

I know OPENCACHING-PL project uses database resources based on Natura 2000 data set.

Thank you.

**Comment by flopp** [comment]
Hm, currently I'm using official NPA shapes from the German administration.
If there is any free/open service providing EU/worldwide NPA data, I could integrate that, too. I will have to to take a look an OC.PL's implementation...

**Comment by harrieklomp** [comment]
I think this is a good site to start when using European data. http://www.eea.europa.eu/data-and-maps/data/natura-5#tab-european-data

**Comment by andrixnet** [comment]
AFAIK OPENCACHING-PL implementation relies on geospacial data in it's database and SQL queries to check whether a cache is inside a NPA region. 
It is quite different from Flopp's Map, which AFAIK uses pure client side JS and third party map tile providers. 
In order to remain so, but implement this, one would have to find such a provider for more countries or even better, for the entire Europe, assuming it exists.

**Comment by flopp** [comment]
ec8b61b: Added experimental CDDA (Common Database on Designated Areas) layer by the European Environment Agency. More info: http://www.eea.europa.eu/data-and-maps/data/nationally-designated-areas-national-cdda-10
