### ISSUE TITLE
Google API new limitations

### ISSUE THREAD

**Issue by andrixnet** [flopp/FloppsMap#65]
I found out from opencaching-pl developer mailing list.

https://developers.google.com/maps/pricing-and-plans/standard-plan-2016-update

According to this, the limits on free use of their API and map data have changed significantly. Since this project dependes directly and heavily on this API, I thought you should know about it ASAP.

**Comment by flopp** [comment]
Thank you for bringing these changes to my attention.

Looking at the usage statistics via [Google's API Dashboard](https://console.developers.google.com), it seems like Flopp's Map is comfortably within the limits - in fact, its usage could grow 10x without problems.

**Comment by andrixnet** [comment]
On the optimist side, the site could grow, so one more thing to keep an eye on it.
Cheers!
