### ISSUE TITLE
Opening flopps.net with firefox ESR 52.6.0

### ISSUE THREAD

**Issue by Mitchsa** [flopp/FloppsMap#84]
Hi, when I try to open https://flopp.net/, I only get the errormessage "An internal server error occurred. Please try again later."

The adress https://flopp-caching.de/ works fine for me.

I'm using Firefox ESR 52.6.0

**Comment by JuicyFruit6** [comment]
Btw, wird hier deutsch gesprochen?

**Comment by JuicyFruit6** [comment]
Auch die Adresse https://www.flopp.net/ funktioniert?

**Comment by JuicyFruit6** [comment]
Könnte Kaspersky da die Finger im Spiel haben?

**Comment by flopp** [comment]
Keine Ahnung - sowas verwende ich nicht ;)
Könntest du es mal mit einem deaktivierten Kaspersky testen?

**Comment by JuicyFruit6** [comment]
Mit ausgeschaltetem Kaspersky das Gleiche. IE geht, Edge auch. Mit Kaspersky!

**Comment by JuicyFruit6** [comment]
Kann man irgendwie die zum Server gesendeten Pakete mitschneiden? Zur Analyse?

**Comment by flopp** [comment]
STRG-SHIFT-Q öffnet die "Netzwerkanalyse" in Firefox.
Wenn du dann auf https://flopp.net gehst (oder ein Reload mit STRG-R) machst, siehst du den Verkehr zwischen Browser und Server. Es wäre sehr interessant zu sehen, was dort in der Liste steht, wenn es schief geht.

**Comment by flopp** [comment]
So sieht das bei mir aus:

![flopp net-ff52-works](https://user-images.githubusercontent.com/272596/36907623-5afe6320-1e39-11e8-8fb1-e3b6b7de12d4.jpg)

**Comment by JuicyFruit6** [comment]
![grafik](https://user-images.githubusercontent.com/27776456/36907905-17c50216-1e3a-11e8-9f3c-f5b496a17d0f.png)


So bei mir

**Comment by JuicyFruit6** [comment]
So mit www.flopp.net

![grafik](https://user-images.githubusercontent.com/27776456/36908039-7a888d5a-1e3a-11e8-9158-d1eee3926d9d.png)

**Comment by JuicyFruit6** [comment]
Problem weiter eingekreist. Habe mal alle Kekse von flopp.net gelöscht. Jetzt geht's!
Defekter Cookie?

**Comment by JuicyFruit6** [comment]
Problem weiter eingekreist :)
Eventuell liegt es auch daran, dass ich die Karte meistens über GC little Helper aufrufe.
Dort werden alle Wegpunkte gleich mit angezeigt. Manchmal erstelle ich auch eigene Wegpunkte dazu. Z.B. bei Mysteries oder so. Können auch mal schnell 100 oder mehr werden.
UND beim Cookie werden diese als Marker mitgeschickt. Der Cookie speichert aber **ALLE Marker** mit ab und das werden **immer mehr.** Irgendwann schafft der Server das Handling mit den vielen Markern scheinbar nicht mehr ?!?

**Comment by JuicyFruit6** [comment]
Bei mehr als 77 gespeicherten Markern fangen die Probleme an.
**Das Problem betrifft auch alle anderen Adressen!!!**
Eevntuell könnte man die Marker beim Beenden löschen - damit sollte alles gut sein?

**Comment by JuicyFruit6** [comment]
Naja, das würde ein anderes Problem eröffnen. Wenn man die Karte ein zweites Mal öffnet wären alle Wegpunkte weg.
Also sollte der Server auch so viele WP verarbeiten können, wie es möglich ist, auf der Karte darzustellen.

**Comment by flopp** [comment]
Ok, das könnte die Erklärung sein. 
Ein ähnliches Problem gibt es beim Teilen einer Karte (+ Marker) per URL; dort gibt es eine Größenbeschränkung auf (glaube ich) ~2000 Zeichen; längere URLs funktionieren dann einfach nicht mehr.

Man sollte die App-Daten statt in Cookies wohl besser in HTML5-LocalStorage ablegen, da hat man vermutlich keine Größen-Probleme. Ich denke, ich gehe das mal an...

**Comment by JuicyFruit6** [comment]
Ja, das mit dem Permalink erstellen hatte ich auch schon.
Wenn das des Rätsels Löung ist, freut es mich wenn ich ich helfen konnte :)
Für so ein klasse Projekt eine Selbstverständlichkeit ;)

**Comment by flopp** [comment]
Mit e24f386ae8d7f8982bee9a6ab194691aa99db53b wird 'localStorage' statt Cookies zum Speichern der Daten verwendet. Hoffe das eliminiert die Probleme in Zukunft.

Nutzer mit einem "internal Server Error" müssen allerdings einmalig ihre Cookies löschen - was natürlich blöd ist, da sie dadurch ihre aktuellen Daten verlieren...

**Comment by JuicyFruit6** [comment]
Das mit dem 'localStorage' scheint zu funktionieren.
Auch längere URLs gehen jetzt.
ABER, bei mehr als 4096 Zeichen kommt vom Server die Fehlermeldung "Request URI is too long".
Auch das Kürzen des Links funktioniert nicht so ganz. Bei mehr als 2083 Zeichen kommt die Fehlermeldung "Error: Invalid Value". ABER das ist wohl ein Problem von https://goo.gl/.
Was dennoch unschön hier ist, ist diese Fehlermeldung. Die bleibt auch bestehen, selbst wenn man danach eine gültige Short URL erzeugen kann?

**Comment by Mitchsa** [comment]
![grafik](https://user-images.githubusercontent.com/27776456/36942539-e323fc42-1f74-11e8-8fa7-a985c25991c4.png)

**Comment by andrixnet** [comment]
@ submitter: Mozilla enterprise list also has people recommending downgrading FF-ESR to 52.1.x due to performance issues of later builds.

**Comment by flopp** [comment]
@Mitchsa jetzt (e53afc649a03d8863c960cf1e21e465268a1a4a1) wird eine Erklärung/Warnung im Permalink-Dialog angezeigt, wenn die URL zu lang ist (>4096 Zeichen); Außerdem wird die Fehlermeldung gelöscht, wenn man den Dialog ein zweites Mal öffnet.

=> damit schließe ich den Issue.
